Naming/HeredocDelimiterNaming:
  Enabled: false
Naming/RescuedExceptionsVariableName:
  Enabled: false
Style/AccessorGrouping:
  Enabled: false
Style/BlockDelimiters:
  Enabled: false
Style/CommentedKeyword:
  Enabled: false
Style/LambdaCall:
  Enabled: false
Style/StabbyLambdaParentheses:
  Enabled: false
Style/StringLiteralsInInterpolation:
  Enabled: false
Style/StringLiterals:
  Enabled: false
Layout/SpaceInsideHashLiteralBraces:
  Enabled: false
Style/TrailingCommaInArguments:
  Enabled: false
Style/TrailingCommaInArrayLiteral:
  Enabled: false
Style/TrailingCommaInHashLiteral:
  Enabled: false
Style/Documentation:
  Enabled: false
Style/ClassVars:
  Enabled: false
Style/ClassAndModuleChildren:
  Enabled: false