name: Hanami RSpec Tests

on: [push, pull_request]

jobs:
  rspec:
    runs-on: ubuntu-latest
    env:
      DATABASE_URL: ${{ secrets.DATABASE_URL }}
      HANAMI_ENV: test
    steps:
      - name: Checkout Repository
        uses: actions/checkout@v2
      - name: Set up Ruby
        uses: actions/setup-ruby@v2
        with:
          ruby-version: 3.2
      # - name: Set up PostgreSQL
      #   uses: docker://postgres:latest
      #   with:
      #     env:
      #       POSTGRES_USER: postgres
      #       POSTGRES_PASSWORD: postgres
      #       POSTGRES_DB: myapp_test
      - name: Install Dependencies
        run: |
          gem install bundler
          bundle install --jobs 4 --retry 3
      - name: Database Setup
        run: |
          bundle exec hanami db prepare
      - name: Run RSpec Tests
        run: |
          bundle exec hanami test
