name: Rspec Tests

on: [push]  # You can adjust the trigger event as needed

jobs:
  build:
    name: Build and Test
    runs-on: ubuntu-latest

    services:
      postgres:
        image: postgres:latest
        ports:
          - "5432:5432"
        env:
          POSTGRES_USER: postgres
          POSTGRES_PASSWORD: postgres
          POSTGRES_DB: myapp_test

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set up Ruby
        uses: ruby/setup-ruby@v1
        with:
          ruby-version: 3.0

      - name: Install dependencies
        run: |
          gem install bundler
          bundle install --jobs 4 --retry 3

      - name: Set up database
        env:
          DATABASE_URL: ${{ secrets.DATABASE_URL }}
        run: |
          bundle exec rake db:migrate

      - name: Run RSpec tests
        env:
          DATABASE_URL: ${{ secrets.DATABASE_URL }}
        run: |
          bundle exec rspec spec
        continue-on-error: false
